[package]
name = "haste"
version = "0.1.0"
authors = ["Tommy Westgeest <wtommywestgeest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.20"
mockito = "0.28.0"
regex = "1.6.0"
