name: Rust

on:
  push:
    branches: [ "master" ]
  on:
      pull_request_target:
        types: [labeled]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests

    # Only run for dependabot PR's
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run cargo test
      run: cargo test

  test_and_get_coverage:
    name: Run tests and get coverage

    # Do not run for dependabot PR's
    if: ${{ github.event.label.name != 'dependencies' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Run cargo tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3.1.0
      with:
        name: code-coverage-report
        path: cobertura.xml
