name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run tests and build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tests
      run: cargo test
    - name: Run codecov
      run: |
        echo "Install codecov"
        curl -Os https://uploader.codecov.io/latest/linux/codecov 
        chmod +x codecov
        echo "Run codecov"
        ./codecov
    - name: Build
      run: cargo build
