name: Test and code coverage

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_get_coverage:
    name: Run tests and get coverage

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Test
      run: cargo test

#    - name: Upload to codecov.io
#      uses: codecov/codecov-action@v3.1.0
#      with:
#        token: ${{secrets.CODECOV_TOKEN}}

#    - name: Archive code coverage results
#      uses: actions/upload-artifact@v3.1.0
#      with:
#        name: code-coverage-report
#        path: cobertura.xml
