name: Test and code coverage

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_get_coverage:
    name: Run tests and get coverage

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install grcov
      run: cargo install grcov

    - name: Install llvm-tools-preview
      run: rustup component add llvm-tools-preview

    - name: Run tests
      run: RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test

    - name: Create coverage folder
      run: mkdir -p target/coverage

    - name: Get coverage
      run: grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/tests.lcov
    
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3.1.0
      with:
        directory: target/coverage
        token: ${{secrets.CODECOV_TOKEN}}
