name: Run tests

on:
  pull_request_target:
    types: [labeled]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests

    # Only run for dependabot PR's
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run cargo test
      run: cargo test